### ISSUE TITLE
Provide a demo instance

### ISSUE THREAD

**Issue by fnkr** [ethanal/Nimbus#24]
(Or at least a few screenshots :))

**Comment by Porco-Rosso** [comment]
+1

**Comment by ethanal** [comment]
Added some screenshots and gave the readme a new look. Let me know if you have any other questions!

**Comment by ethanal** [comment]
There's also a new release out (https://github.com/ethanal/Nimbus/releases/tag/v1.2.0) for the menu bar app if you've already downloaded one of the older ones.
